"""Add Company Code

Revision ID: 3c0b9326c88d
Revises: 9692c76b7ae3
Create Date: 2025-04-17 23:09:21.100446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0b9326c88d'
down_revision = '9692c76b7ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_code', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['company_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('company_code')

    # ### end Alembic commands ###
